### ISSUE TITLE
Add indexes to more annotations in the tsv that have coordinates

### ISSUE THREAD

**Issue by jzook** [nspies/genosv#38]
It's great that you've added indexes as a prefix to many of the tsv annotations that previously only contained coordinates that varied from site to site.  Could you also add similar indexes to the other annotations that have coordinates, like:
overlap_..._part
count_..._part
extension_..._part

Thanks!

**Comment by jzook** [comment]
@lesleymaraina is ready to start trying to use your annotations from genosv in her machine learning model soon.  Adding indexes to these annotations that have coordinates would make parsing them much easier - would this be an easy feature for you to add?  Thanks!

**Comment by nspies** [comment]
@lesleymaraina @jzook 

Alright, the latest version now includes a numerical ID for each of the count/overlap/extension results. To parse this, you'll need to consider both the number as well as the allele. For example, these are the three extension counts:

extension_0.alt_part:1190-1190+
extension_1.alt_part:2080-2080+
extension_0.ref_part:1190-1190+

So there is a 0.alt_part, a 1.alt_part, and a 0.ref_part.
