### ISSUE TITLE
Use REF and ALT for all sequence-defined variants

### ISSUE THREAD

**Issue by jzook** [nspies/genosv#39]
Right now, if we call a complex net deletion where there is both an insertion and a deletion, and the SVTYPE=DEL, svviz treats it as a simple del and doesn't use REF and ALT.  I'd prefer if it defaulted to using REF and ALT if it is provided.  I'd probably prefer the same thing for SVTYPE=INV, since these are also often complex.

**Comment by nspies** [comment]
closed by a81973f9579d85ab7b7cb4a7fae6ec7e46b8583c
