### ISSUE TITLE
Name of bam file missing to separate reads in pdf

### ISSUE THREAD

**Issue by jzook** [nspies/genosv#43]
You used to have the name of the bam files to know which reads came from each bam file in the pdf, and these now seem to be missing.  I've attached a couple examples, and here is the command I ran, though you might want to just grep these 2 IDs from the vcf since otherwise it'll run 100 sites:

`genosv --also-plot-context 4000 --outdir /scratch/PI/msalit/jzook/AJTrio/svvizconfirm/union_170509/genosv20a1PBv030bPASSbionanodiffgt300 --ref /scratch/PI/msalit/jzook/references/human_g1k_v37.fasta -V /scratch/PI/msalit/jzook/AJTrio/svvizconfirm/union_170509/union_170509_refalt.2.2.2.clustered.simpleINFO.techcounts.bionanodiffgt300.vcf.gz /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG002_PB_70x.bam,sequencer=pacbio /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG003_PB_30x.bam,sequencer=pacbio /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG004_PB_30x.bam,sequencer=pacbio
`

[HG2_PB_SVrefinePBcRDovetail_7719.del_X_91678133.pdf](https://github.com/nspies/genosv/files/1285009/HG2_PB_SVrefinePBcRDovetail_7719.del_X_91678133.pdf)

[HG2_PB_SVrefinePBcRDovetail_7571.SequenceDefinedVariant.22_50933765-50933765.pdf](https://github.com/nspies/genosv/files/1285029/HG2_PB_SVrefinePBcRDovetail_7571.SequenceDefinedVariant.22_50933765-50933765.pdf)

**Comment by nspies** [comment]
This should be fixed with nspies/genomeview@d46a9f295e47464a08b2037d8bd9f80cad342067 -- make sure to update your genomeview with ``pip install -U genomeview``
